steps:
  # Build the docker image
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_TERMINUS_SITE:PR-$_PR_NUMBER', '.' ]

  # Push the image to GCR
  - name: gcr.io/cloud-builders/docker
    args: [ 'push', 'gcr.io/$PROJECT_ID/$_TERMINUS_SITE:PR-$_PR_NUMBER' ]

  # Deploy the image to cloud run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - $_TERMINUS_SITE-pr-$_PR_NUMBER
      - '--image'
      - gcr.io/$PROJECT_ID/$_TERMINUS_SITE:PR-$_PR_NUMBER
      - '--region'
      - us-central1
      - '--platform'
      - managed
      - '--allow-unauthenticated'
      - '--max-instances'
      - "2"
      - '--no-traffic'
      - "--update-env-vars"
        "TERMINUS_SITE=${_TERMINUS_SITE},TERMINUS_ENV=pr-${_PR_NUMBER}"

images:
  - gcr.io/$PROJECT_ID/$_TERMINUS_SITE:PR-$_PR_NUMBER